services:
  uptime-kuma:
    image: louislam/uptime-kuma:2
    container_name: uptime_kuma
    restart: always
    expose:
      - 3001
    volumes:
      - ./data:/app/data
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - VIRTUAL_PORT=3001
    networks:
      - default
      - reverse-proxy

networks:
  reverse-proxy:
    external: true
